from project.animals.birds import Owl, Hen
from project.food import Food, Vegetable, Meat, Fruit, Seed
from project.animals.mammals import Tiger, Cat, Dog, Mouse

owl = Owl("Pip", 10, 10)
print(owl)
meat = Meat(4)
print(owl.make_sound())
owl.feed(meat)
veg = Vegetable(1)
print(owl.feed(veg))
print(owl)

# hen = Hen("Harry", 10, 10)
# veg = Vegetable(3)
# fruit = Fruit(5)
# meat = Meat(1)
# print(hen)
# print(hen.make_sound())
# hen.feed(veg)
# hen.feed(fruit)
# hen.feed(meat)
# print(hen)

# tiger = Tiger("XXX", 10, "Sofia")
# print(tiger)
# meat = Meat(4)
# print(tiger.make_sound())
# tiger.feed(meat)
# veg = Vegetable(1)
# print(tiger.feed(veg))
# print(tiger)

# cat = Cat("XXX", 10, "Sofia")
# print(cat)
# meat = Meat(4)
# print(cat.make_sound())
# cat.feed(meat)
# fruit = Fruit(1)
# print(cat.feed(fruit))
# print(cat)

# mouse = Mouse("XXX", 10, "Sofia")
# print(mouse)
# meat = Meat(4)
# print(mouse.make_sound())
# mouse.feed(meat)
# seed = Seed(1)
# print(mouse.feed(seed))
# print(mouse)

# dog = Dog("XXX", 10, "Sofia")
# print(dog)
# meat = Meat(4)
# print(dog.make_sound())
# dog.feed(meat)
# fruit = Fruit(1)
# print(dog.feed(fruit))
# print(dog)

